### PR TITLE
Switch over to Hyper 0.12

### PR DESCRIPTION
**Pull request by palfrey**
This is the start of work towards Hyper 0.11 (which is #11). It's very much a WIP with lots of hacks and doesn't even fully compile yet.

I was trying to build a `Service` for `SequentialConnector` as the first example of the right path. Initial version just dumped the buffer straight in the `call`, but then Hyper complains because it hasn't gotten around to sending out it's request yet. I then built `MockHttpStream` to be a `AsyncRead/Write` stream that would wait until the request came in, then send out the response immediately. This sometimes worked, but never appeared to get the call for the response after the request came in, so I wrapped it in `MockPollStream`, which now gets the response data request. However, the response bit never gets called again, so it can't send Hyper the 0-length read that means EOF and so it stalls there entirely.

Right now, only the `connector` test even compiles (I could do the `macros` bit, but I was still reshuffling things and wanted to reduce the rewrite time until I've got an approach figured out). Advised command line to see everything it does is
`RUST_LOG=trace,jobserver=warn,rustc=warn,cargo=warn cargo test --test connector -- --nocapture`

I've spent some time digging through Tokio, mio and Hyper, and really can't figure out what I'm doing wrong. Suggestions welcomed!

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing. Unfortunately I have to tell you that there were the following issues with your Pull Request

 * Commit: deb518683b2c765bbf6d7e5ea859f49373937fce
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 1077ca8d119c6da1c45620086378f506b46aef20
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by Byron** [comment]
Thanks a lot, @palfrey , for your attempt to update this library! It's very much appreciated!
Right now I find myself unable to help as I have no idea anymore how `hyper` looks like these days.
However, I think that will change when [this improvement to google-apis-rs](https://github.com/Byron/google-apis-rs/issues/189) gets actively developed.

**Comment by bkda** [comment]
Amazing work, I'm trying to make some tests for hyper too, and can't find mock library, waitting for it.

**Comment by palfrey** [comment]
So, as it turns out the Hyper 0.12 release fixed the "not calling again" problem (I suspect bits of tokio upgrades in https://github.com/hyperium/hyper/releases/tag/v0.12.0 helped), and this is now a functional working branch :)

@Byron: If you're happy with the overall code, I can redo the commit messages and so on in line with your schema, now this isn't just a WIP branch.

**Comment by Byron** [comment]
This looks wonderful! Thanks so much - I will cut a new release momentarily!

**Pull request merged**
